//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPermisos.SGPServiceAsistencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGPServiceAsistencia.ISGPService")]
    public interface ISGPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/SQL_GET_DATASET", ReplyAction="http://tempuri.org/ISGPService/SQL_GET_DATASETResponse")]
        System.Data.DataSet SQL_GET_DATASET(string sql, string sDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/SQL_GET_DATASET", ReplyAction="http://tempuri.org/ISGPService/SQL_GET_DATASETResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SQL_GET_DATASETAsync(string sql, string sDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/SQL_NON_QUERY", ReplyAction="http://tempuri.org/ISGPService/SQL_NON_QUERYResponse")]
        void SQL_NON_QUERY(string sSQL, string sDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGPService/SQL_NON_QUERY", ReplyAction="http://tempuri.org/ISGPService/SQL_NON_QUERYResponse")]
        System.Threading.Tasks.Task SQL_NON_QUERYAsync(string sSQL, string sDB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISGPServiceChannel : GestionPermisos.SGPServiceAsistencia.ISGPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SGPServiceClient : System.ServiceModel.ClientBase<GestionPermisos.SGPServiceAsistencia.ISGPService>, GestionPermisos.SGPServiceAsistencia.ISGPService {
        
        public SGPServiceClient() {
        }
        
        public SGPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SGPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SQL_GET_DATASET(string sql, string sDB) {
            return base.Channel.SQL_GET_DATASET(sql, sDB);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SQL_GET_DATASETAsync(string sql, string sDB) {
            return base.Channel.SQL_GET_DATASETAsync(sql, sDB);
        }
        
        public void SQL_NON_QUERY(string sSQL, string sDB) {
            base.Channel.SQL_NON_QUERY(sSQL, sDB);
        }
        
        public System.Threading.Tasks.Task SQL_NON_QUERYAsync(string sSQL, string sDB) {
            return base.Channel.SQL_NON_QUERYAsync(sSQL, sDB);
        }
    }
}
